// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM9OE1Z4ByRUAzEfMPfZhlP_ROPtBpoVU',
    appId: '1:585664681257:web:efbd9059ba361ded7a9338',
    messagingSenderId: '585664681257',
    projectId: 'ticketing-app-b359a',
    authDomain: 'ticketing-app-b359a.firebaseapp.com',
    storageBucket: 'ticketing-app-b359a.firebasestorage.app',
    measurementId: 'G-YQP0EPGF7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY9y5PFyjF8OeUF0ZCusK-GetG32OLZ6w',
    appId: '1:585664681257:android:a396b565ee72dad17a9338',
    messagingSenderId: '585664681257',
    projectId: 'ticketing-app-b359a',
    storageBucket: 'ticketing-app-b359a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUYbfpYYGcJQp_B5gHPh_Adxw9_PtlS3U',
    appId: '1:585664681257:ios:fec252bb01e1fae07a9338',
    messagingSenderId: '585664681257',
    projectId: 'ticketing-app-b359a',
    storageBucket: 'ticketing-app-b359a.firebasestorage.app',
    iosBundleId: 'com.example.ticketingApp',
  );

}